FROM node:25-alpine AS build
WORKDIR /app

RUN npm i -g pnpm@9.0.0

COPY package.json pnpm-lock.yaml ./

RUN pnpm install --frozen-lockfile

COPY . .

CMD ["pnpm", "run", "dev", "--host", "0.0.0.0", "--port", "80"]
