export { api } from './services/client'
export { courseService } from './services/courses'
export { archiveService } from './services/archives'
export { authService } from './services/auth'
export { memeService } from './services/meme'
export { statisticsService } from './services/statistics'
export { aiExamService } from './services/aiExam'
export { notificationService } from './services/notifications'
export { discussionService } from './services/discussion'
export { userService } from './services/users'
export * from './services/admin'
