"""add archive discussion messages and user nickname

Revision ID: 01075665e961
Revises: 3d608a21fb34
Create Date: 2025-12-21 12:11:06.152322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '01075665e961'
down_revision: Union[str, Sequence[str], None] = '3d608a21fb34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('archive_discussion_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('archive_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['archive_id'], ['archives.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_archive_discussion_messages_archive_id'), 'archive_discussion_messages', ['archive_id'], unique=False)
    op.create_index(op.f('ix_archive_discussion_messages_user_id'), 'archive_discussion_messages', ['user_id'], unique=False)
    op.alter_column('memes', 'content',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.alter_column('memes', 'language',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.add_column('users', sa.Column('nickname', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_users_nickname'), 'users', ['nickname'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_nickname'), table_name='users')
    op.drop_column('users', 'nickname')
    op.alter_column('memes', 'language',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('memes', 'content',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_index(op.f('ix_archive_discussion_messages_user_id'), table_name='archive_discussion_messages')
    op.drop_index(op.f('ix_archive_discussion_messages_archive_id'), table_name='archive_discussion_messages')
    op.drop_table('archive_discussion_messages')
    # ### end Alembic commands ###
